services:
  # Aplicação Next.js em modo desenvolvimento
  web-app-dev:
    image: node:18-alpine
    container_name: web-snmp-dev
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://app:apppass@postgres:5432/appdb?schema=public
      - ANSIBLE_API_URL=http://ansible-api:5000
      - ZABBIX_URL=http://zabbix-web:8080/api_jsonrpc.php
      - ZABBIX_USER=Admin
      - ZABBIX_PASSWORD=zabbix
      - JWT_SECRET=sua-chave-secreta-muito-segura
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npx prisma generate && npm run dev"
    depends_on:
      - postgres
      - ansible-api
      - zabbix-web
    networks:
      - web-snmp-network

  # Banco PostgreSQL principal
  postgres:
    image: postgres:16
    container_name: web-snmp-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - web-snmp-network

  # API do Ansible
  ansible-api:
    build: ./ansible-api
    container_name: web-snmp-ansible-api-dev
    restart: unless-stopped
    environment:
      ANSIBLE_INVENTORY: /ansible/inventories/dev/hosts.ini
    volumes:
      - ./ansible:/ansible
    ports:
      - "5000:5000"
    depends_on:
      - mock-switch
    networks:
      - web-snmp-network

  # Switch simulado para testes
  mock-switch:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: web-snmp-mock-switch-dev
    restart: unless-stopped
    environment:
      PASSWORD_ACCESS: "true"
      USER_NAME: "admin"
      USER_PASSWORD: "admin123"
      SUDO_ACCESS: "false"
    ports:
      - "2222:2222"
    networks:
      - web-snmp-network

  # Banco PostgreSQL para Zabbix
  zabbix-postgres:
    image: postgres:15
    container_name: web-snmp-zabbix-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - zabbix-db-dev:/var/lib/postgresql/data
    networks:
      - web-snmp-network

  # Servidor Zabbix
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    container_name: web-snmp-zabbix-server-dev
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    depends_on:
      - zabbix-postgres
    ports:
      - "10051:10051"
    networks:
      - web-snmp-network

  # Interface Web do Zabbix
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    container_name: web-snmp-zabbix-web-dev
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    depends_on:
      - zabbix-postgres
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - web-snmp-network

  # Prisma Studio para desenvolvimento
  prisma-studio:
    image: node:18-alpine
    container_name: web-snmp-prisma-studio-dev
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://app:apppass@postgres:5432/appdb?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5555:5555"
    command: sh -c "npm install && npx prisma studio --hostname 0.0.0.0"
    depends_on:
      - postgres
    networks:
      - web-snmp-network

volumes:
  pgdata-dev:
  zabbix-db-dev:

networks:
  web-snmp-network:
    driver: bridge