---
- name: Cisco IOS - show version
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: out
    - name: Print output
      ansible.builtin.debug:
        var: out.stdout_lines
